### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#1]
Implement google analytics on the site and share info with Henry so he can archive data

**Comment by jenhicks** [comment]
@mattpetrucci

**Comment by jenhicks** [comment]
Matt created the tag and now just need to add the site (if someone hasn't done this already). @keenon did you add? If not @aymanhab could likely work on this when he is back in the office next week.

**Comment by aymanhab** [comment]
The hook for analytics has been merged but we still need more granular analytics and to confirm once the code change propagates to public facing server.
