### ISSUE TITLE
Web UI loads annoyingly slowly

### ISSUE THREAD

**Issue by keenon** [keenon/AddBiomechanics#130]
This is because we're loading an entire index of S3 every time we refresh the page. We really shouldn't do this, it'd be much better to load just our relevant section of S3 (just your files, or even better, just the subject whose link you're looking at).

**Comment by AlbertoCasasOrtiz** [comment]
I was going to create an issue about this. I think this could be tackled at the same time as https://github.com/keenon/AddBiomechanics/issues/59

**Comment by nickbianco** [comment]
Possible temporary fix: change the landing page to the user's page, and only load the user's data (if this indeed an easy fix).
