### ISSUE TITLE
Typo in text under "Mark Dataset as Finalized" button

### ISSUE THREAD

**Issue by nickbianco** [keenon/AddBiomechanics#163]
<img width="174" alt="image" src="https://github.com/keenon/AddBiomechanics/assets/23224439/b9f1cd85-20e2-4c7d-bbdc-846e48d30ad9">

It should read: "You can always mark it as a _draft_..."

**Comment by nickbianco** [comment]
Also: on Data Sharing Mission page "Unfinalized Draft" typo (quotes are mangled).

**Comment by nickbianco** [comment]
It seems like all double quotes are mangled on the front end.

<img width="282" alt="image" src="https://github.com/keenon/AddBiomechanics/assets/23224439/64232f51-fedb-4d3f-a9b4-c2bab0bb7192">

**Comment by nickbianco** [comment]
@AlbertoCasasOrtiz: if the mangled quotes should be separate issue, let me know.

**Comment by AlbertoCasasOrtiz** [comment]
@nickbianco Thank you Nick, I don't think it should be a separate issue. It is already solved and we only have to figure out how to deploy the static page. I'll ask Keenon about deploying this once he is back.

**Comment by nickbianco** [comment]
Ah, I see. Thanks!
