### ISSUE TITLE
Fewer than 8 markers?

### ISSUE THREAD

**Issue by whl-007** [keenon/AddBiomechanics#171]
![image](https://github.com/keenon/AddBiomechanics/assets/120098257/2fd288eb-e696-4a98-af06-a5678683320c)
The system error message is: "There are fewer than 8 markers that show up in the OpenSim model and in trial 1",but I inputted 25 markers.

**Comment by nickbianco** [comment]
Hi @whl-007, thank you reporting this potential issue. This question is better suited for the AddBiomechanics forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2402&pluginname=phpBB.

Please post your question there and we can address it.

**Comment by whl-007** [comment]
Thank you very much！




王浩龙
***@***.***







                       
Original Email
                       
                     

Sender:"Nicholas Bianco"< ***@***.*** &gt;;

Sent Time:2023/10/3 7:09

To:"keenon/AddBiomechanics"< ***@***.*** &gt;;

Cc recipient:"whl-007"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [keenon/AddBiomechanics] Fewer than 8 markers? (Issue #171)




 
Hi @whl-007, thank you reporting this potential issue. This question is better suited for the AddBiomechanics forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2402&amp;pluginname=phpBB.
 
Please post your question there and we can address it.

**Comment by whl-007** [comment]
> Hi @whl-007, thank you reporting this potential issue. This question is better suited for the AddBiomechanics forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2402&pluginname=phpBB.
> 
> Please post your question there and we can address it.

I am trying now.If I can do it,I will tell you.
