### ISSUE TITLE
Update website and app with new logo and recommended colors

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#2]
Incorporate new graphics in the web site/app, including logos and updated colors.

Button color guidance:
#2C579E matches the color scheme and passes accessibility contrast
#4a71b3 is a darker color he can use for the hover state.

Sent over logos via email.

**Comment by jenhicks** [comment]
@aymanhab

**Comment by aymanhab** [comment]
@keenon I updated the files locally but couldn't push to github due to permissions, can you update settings to allow me to make PRs. You'll need to review and approve before merging anything. Thanks

**Comment by aymanhab** [comment]
git.exe push --set-upstream --progress "origin" update_logos
remote: Permission to keenon/AddBiomechanics.git denied to aymanhab.
fatal: unable to access 'https://github.com/keenon/AddBiomechanics.git/': The requested URL returned error: 403


git did not exit cleanly (exit code 128) (1859 ms @ 11/15/2022 12:24:48 PM)

**Comment by aymanhab** [comment]
@keenon The site should update on the next push to dev I assume but I'm not sure if this is automated. I'll send you a separate message regarding credentials. Please let me know if anything breaks in terms of L&F

**Comment by jenhicks** [comment]
@aymanhab The logo isn't showing up for me properly here (person) is missing: https://dev.addbiomechanics.org/data/35e1c7ca-cc58-457e-bfc5-f6161cc7278b/SprinterTest

Would also be helpful to make the add biomechanics text larger.

**Comment by aymanhab** [comment]
I followed the link and the person showed as expected, maybe Keenon fixed
something or I'm looking at the wrong place. I'm on the way in so we can
fix it on the spot as needed.

**Comment by aymanhab** [comment]
You're correct @jenhicks the "logo with text" is missing the person (it's there but in white). Will fix

**Comment by aymanhab** [comment]
How about this @jenhicks 
![Screenshot 2022-12-08 143943](https://user-images.githubusercontent.com/3972208/206582310-c9a5f080-baee-407b-82c6-cb519dcc45c3.png)

**Comment by jenhicks** [comment]
The new logo looks good. Thanks @aymanhab  The text is "squashed" though. I would either reproduce in the exact same aspect ratio as the pdf; or you could go back to the previous text/font.

**Comment by jenhicks** [comment]
the letters are more narrow and close together than in the logo pdf.

**Comment by aymanhab** [comment]
Thanks @jenhicks The latest incarnation here https://github.com/keenon/AddBiomechanics/pull/9 was copied from pdf and uniformly scaled in illustrator, if that still looks distorted or you prefer a page screen capture please let me know.

**Comment by jenhicks** [comment]
Ok; that does look correct in the files changed log. is that what's live on the dev server?

**Comment by aymanhab** [comment]
Not yet, will merge the PR and then it will be pushed to the dev server by Keenon later.
