### ISSUE TITLE
Attribution at the folder level

### ISSUE THREAD

**Issue by mattpetrucci** [keenon/AddBiomechanics#214]
Currently attribution (citations, etc.) are at the subject level on the dev server, but you are unable to add attribution to a folder and have it apply to entire study.

**Comment by mattpetrucci** [comment]
If someone has previous enter attribution and the folder level, is it also in the subject level attribution field in the new interface?

**Comment by AlbertoCasasOrtiz** [comment]
@mattpetrucci Yes, if someone had attribution info in the previous version, it should be available now too.

**Comment by AlbertoCasasOrtiz** [comment]
Tasks:

 - [x] Recover attribution from previous version and create new layout to include it.
 - [ ] Inherit attribution from parent folders, but allow to have its own attribution.
