### ISSUE TITLE
Consistency of "folder" and "dataset"

### ISSUE THREAD

**Issue by mattpetrucci** [keenon/AddBiomechanics#216]
Currently, when you create a folder it shows up in the list as a "dataset." We could make these consistent so they are either both folder or both dataset.

**Comment by AlbertoCasasOrtiz** [comment]
@mattpetrucci @keenon @jenhicks Hi everyone. Which one should we use, folder or dataset? Once we decide I could change it everywhere.

**Comment by mattpetrucci** [comment]
I would lean towards using dataset, just so its inherently obvious that you may want to aggregate your subjects into a dataset. But I'm open to either

**Comment by AlbertoCasasOrtiz** [comment]
I agree on dataset too. I think it is more intuitive and aligns better with addbiomechanics mission

**Comment by mattpetrucci** [comment]
We can split this into a different issue if you prefer, but I also just realized that you aren't able to change dataset or subject names after they are created. We may want to have that option.

**Comment by AlbertoCasasOrtiz** [comment]
I checked and there is already an issue for changing names of folders and subjects: https://github.com/keenon/AddBiomechanics/issues/92

**Comment by mattpetrucci** [comment]
Great, thanks for finding. Is that a difficult change to implement?

**Comment by AlbertoCasasOrtiz** [comment]
I am not sure, but I think at some point last year we discussed it and it is not easy due to how AWS works? I think @keenon will know better
