### ISSUE TITLE
Delete button would cause deletion of subjects with the same name pattern.

### ISSUE THREAD

**Issue by TheOne-1** [keenon/AddBiomechanics#239]
I have three independent subjects named "sub0", "sub0_split0", and, "sub0_split1". When I tried to delete "sub0", the other two subjects got deleted as well.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @TheOne-1, thank you for reporting this issue, I will look into it as soon as possible.

**Comment by AlbertoCasasOrtiz** [comment]
I just fixed this on the dev server. Let me know if that fixed it for you.
