### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [keenon/AddBiomechanics#24]
During today's meeting, people is complaining about error messages not being descriptive.

(@nickbianco's edit) Things we should warn/tell users about:
- [ ] An OpenSim model file exists
- [ ] The OpenSim model file is the latest (4.0) format
- [ ] A TRC or C3D file exists
- [ ] The markers in the TRC file are in the correct format
- [ ] The forces in the MOT file are in the correct format (if it exists)

**Comment by keenon** [comment]
I used to have the code setup so that on a crash, the server would still upload `log.txt` to S3, so that the frontend could display the error log along with the "Your subject crashed" message. Somewhere along the line, that feature stopped working. It'd be a great first step to see if we can get those `log.txt` files to display properly again.

**Comment by nickbianco** [comment]
I learned recently that putting the ground reaction force info from a MOT file into a TRC file (don't ask) will cause a crash (segfault) when running `engine.py`, so we could use that as a test case.

**Comment by nickbianco** [comment]
To summarize some recent discussions, we should:

1. Renable the uploading of logs to S3.
2. Provide generic error messages when certain stages of AddBiomechanics fail (e.g., data input, scaling/IK, GRF detection, dynamics fitting).
3. Send error messages to frontend with suggestions for debugging.

**Comment by AlbertoCasasOrtiz** [comment]
For the frontend after discussion with Keenon:

1. If there are errors, show them always.
2. If there are warnings:
  a. Allow users to dismiss warnings that they fixed or don't want to attend to.
  b. If user dismissed all of the warnings, add a button "Show Warnings".
3. Add quick options besides the error/warnings (e.g., a warning recommends to activate a checkbox from advanced options, show that checkbox with the error/warning for quick action).
