### ISSUE TITLE
Add flag file for state "Waiting for Server"

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [keenon/AddBiomechanics#250]
Tasks (Frontend and Backend):
 - [ ] Create flag file (called `waitingForServerFlag` or something similar) when user click "Process" or "Reprocess".
 - [ ] Remove flag file when the task is queued in slurm.
 - [ ] Remove an old file and create a new one when "Process" or "Reprocess" is clicked (so it updated the creation date).

Tasks (Frontend):
 - [ ] Check for presence of the `waitingForServerFlag`.
 - [ ] If it exists and has been created more than 24 hours ago, ask user to reprocess.

 **Note:** Looks like flag files are created and removed in frontend or backend as needed?

**Comment by AlbertoCasasOrtiz** [comment]
@nickbianco I noticed that a flag for "Waiting for Server" is equivalent to:

```
readyFlagExists && !resultsExist && !errorFlagExists && !processingFlagExists && !slurmFlagExists
```

So I am using this expression for now. We could create a variable in the frontend for it without specifically having to create a flag and pollute the file system with more files.

**Comment by nickbianco** [comment]
@AlbertoCasasOrtiz sounds good!
