### ISSUE TITLE
Warning for suspecious meta data (e.g., massKg)

### ISSUE THREAD

**Issue by TheOne-1** [keenon/AddBiomechanics#264]
I image wrong meta data such as height and weight can mess up with DynamicFitter engine. 

For example, the body weight of subject P10 of [this study](https://www.cambridge.org/core/journals/wearable-technologies/article/wearable-realtime-kinetic-measurement-sensor-setup-for-human-locomotion/488C21B7706FFDFA7FFAB387FD0A1A64) is reported as 61.6Kg. However, the [static trial](https://drive.google.com/open?id=1jXOAUA3CUrZMCW_pY3f6MOtiiPKqJy1H&usp=drive_fs) has a total GRF of ~700N, corresponding to ~71Kg.

Would it make sense to check the weight based on trials with low acceleration across all the body segments?

**Comment by nickbianco** [comment]
We already adjust the mass of the model based on the GRF data, so the user input will be corrected. 

Incorrect height data will skew the kinematics fitter results, but I think we still want to respect user inputs. If we did adjust inputs, I'd want to ensure that "good" input data isn't modified incorrectly. In many cases the height information is useful when marker data is limited (i.e., there is typically no markers on the head).

**Comment by TheOne-1** [comment]
Ok good to know that the GRF is already being adjusted. Maybe just for the AddBiomechanics dataset where GRF estimation is the main focus, we need to warn users of suspicious body weight.
