### ISSUE TITLE
Citation for dataset and populating subjects within 

### ISSUE THREAD

**Issue by mattpetrucci** [keenon/AddBiomechanics#279]
When I created a new dataset, added a citation to the dataset, and then created subjects within the dataset, the new subject wizard did not populate the citation from the dataset. We may be able to either get rid of the citation entry per subject, or find a way to populate that data forward to the subjects so it doesn't have to be entered with each new subject.

**Comment by AlbertoCasasOrtiz** [comment]
In I'm not wrong, the citation field in subject was added when the new version of the GUI was added and the citation fields for datasets didn't exist (until we recovered it). Now that we have citation for each dataset, I would suggest removing the citation field from subjects.

**Comment by mattpetrucci** [comment]
Agreed

**Comment by jenhicks** [comment]
Agreed, also. Though we should make sure we don't lose any citation info that folks have already entered.
