### ISSUE TITLE
Processing email link does not work, suggested new wording

### ISSUE THREAD

**Issue by mattpetrucci** [keenon/AddBiomechanics#280]
When I processed some data, the link that was provided did not like to my dataset. The link was https://addbiomechanics.org/my_data/Study1/Sub01. Does the full path needs to be changed so it is addbiomechanics.org/data/<UserID>/Study1/Sub01?

Also, a minor suggestion to the last line, instead of saying:

"P.S: Do not reply to this email. To give feedback on AddBiomechanics or if you have questions, please visit the AddBiomechanics forum on SimTK: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2402&pluginname=phpBB"

we could say:

 “Having problems or questions? Do not reply to this email. Please visit the AddBiomechanics forum on SimTK: https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=2402&pluginname=phpBB”

**Comment by AlbertoCasasOrtiz** [comment]
You are right, it should be "data" instead of "my_data", I will change it.

I agree on the suggestion too.

**Comment by mattpetrucci** [comment]
Just confirmed thehyperlink works and the message is updated. We can close this issue.
