### ISSUE TITLE
Create a design doc for custom data analytics

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#3]
Create scripts or other tools to provide additional analytics for site usage and data shared. First phase is to provide this on the backend and in future phases, we can display select stats on the site. 

Initial analytics we are interested in:
- Number of users and number of uploads per user
- Amount of data for users in private sandbox vs. draft vs. publicly shared
- Usage of participant and trial level tags
- How many email domains are in use and which are responsible for significant amounts of data? (In future, when we have more profile data, could pull stats for institutions)
- What models are being used most commonly?

@keenon other ideas? can we pull things like any accuracy measures, warnings? Also seems fine to start with a small set and build from there.

@aymanhab ... heres an issue bringing over the content from the spreadsheet.

**Comment by jenhicks** [comment]
Also need to make sure google analytics data is getting archived by Henry.

**Comment by jenhicks** [comment]
@hykwong

**Comment by mattpetrucci** [comment]
Just noticed this issue. I think we can close this now.
