### ISSUE TITLE
Refinements to User Profile Page Creation and Display

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#39]
- [x] Change fields to "First Name" and "Last Name (Surname)"
- [x] Do not display email addresses (change to "Contact")
- [x] Add a link to a user's shared datasets
- [x] Fix website link so it shows properly the `https://` part
- [x] Fix bug that makes the profile to disappear
- [x] Profile images placeholder
- [x] Profile menu and image at top right
- [x] Create a way to ping current users to invite them to create a profile page (likely wait to push until public data sharing and metadata are ready also)
- [x] Increase the display time of toast advising users to create profile
- [x] footer covering edit box
- [x] Move to production server

**Comment by mattpetrucci** [comment]
@AlbertoCasasOrtiz I was just testing out my profile page and for some reason the https:// loses the colon when you click it.

**Comment by mattpetrucci** [comment]
Also, this is not an immediate need, but something I didn't consider until now (and sorry if I've missed this before) is whether we should allow links or access between users in the same group. For example, a PI is probably not going to be the one uploading and processing the data. Maybe it's as simple as adding a "PI" field that can have the link to the PIs page? Or PIs could have the student profiles on their page?

Could we structure it like SimTK where projects have multiple people on the team?

**Comment by AlbertoCasasOrtiz** [comment]
@mattpetrucci I've been trying to replicate it but I couldn't. Massive that is related to the current bug. What browser are you using? Did you do something specific for it to happen?

**Comment by mattpetrucci** [comment]
@AlbertoCasasOrtiz I'm on chrome. 

<img width="775" alt="Screenshot 2023-03-22 at 2 54 26 PM" src="https://user-images.githubusercontent.com/48534856/227047282-4437a17c-eaa3-413f-ba64-18dfc03ab221.png">

I am just clicking the hyper link here. As you can see it has the address correct, but if I hover, you can see what link its trying to go to in this screen shot: 

<img width="313" alt="Screenshot 2023-03-22 at 2 55 03 PM" src="https://user-images.githubusercontent.com/48534856/227047378-1d1e1427-bafd-41e5-accd-783ddaa97088.png">

**Comment by AlbertoCasasOrtiz** [comment]
There is some progress on this. Keenon solved some bugs, including the bug with the profile page, and I completed some of the tasks. Everything is in the dev server now.

@jenhicks @mattpetrucci @keenon Regarding **Create a way to ping current users to invite them to create a profile page (likely wait to push until public data sharing and metadata are ready also)**, What do you think about showing a Toast when the user logs in, that asks him/her to fill their information in the profile page? An email can be easily missed, but a Toast in the screen will be seen by everyone. The toast would only be shown if the `profile.json` file does not exist.

**Comment by jenhicks** [comment]
Thanks @AlbertoCasasOrtiz ! These updates are looking great.

A few comments:
(1) For the default profile image, I would use something like this: https://commons.wikimedia.org/wiki/File:Default_pfp.svg (not the logo for AddBiomechanics, which is a little confusing)

(2) There is a minor layout issue when editing your profile (see attached screen cap)

(3) I like that idea to use a toast (vs. bothering people with emails)

What does the sign-up experience now look like for new users? Do they have to create a user profile and what info in the profile is required?

Jen

**Comment by jenhicks** [comment]
![Screen Shot 2023-03-28 at 1 49 42 PM](https://user-images.githubusercontent.com/4510959/228364031-d374879e-4095-4002-acdf-40a029dd47b5.png)

**Comment by AlbertoCasasOrtiz** [comment]
Should I create a new issue for allowing users to upload profile images? Right now we have just a placeholder, and it looks like a big enough issue to be isolated from this one.

**Comment by jenhicks** [comment]
Good idea @AlbertoCasasOrtiz !
