### ISSUE TITLE
Refinements to public data sharing feature

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#40]
User Folder Annotation:
- [x] Add complete set of annotations to a folder based on previous planning discussions (@mattpetrucci can provide those specs ... please add to the issue)
- [x] Determine and implement desired behavior for subfolders as far as annotation and draft vs. non-draft mode (e.g., use parent info unless otherwise specified)
- [x] Clarify for the user which folder they are annotating (i.e., display the folder name in the sidebar)
- [x] Allow user to change the name of the folder and subject (might want to make this a separate issue, as is likely more complex than other tasks listed here)
- [x] Add field to list the Team for a given project. Down the line we could pull in users, but for now just a list of names seems sufficient
- [x] Citation and funding are not shown when you access another person's folder.

Public Folder Display:
- [x] Show user name (if available) rather than code
- [x] Link displayed user name to the user's profile
- [x] Display correct tags (just see placeholder for now)
- [x] Display full metadata for the folder (from the user annotation notes above)
- [x] Remove leading forward slash in folder names?
- [x] In search remove text that says "Placeholder" 
- [x] When you search and hit "return" it doesn't give you your results (looks like the full data)

**Comment by jenhicks** [comment]
I updated this checklist based on the recent commit. Thanks @AlbertoCasasOrtiz 

Some of the items might need more discussion (E.g., subfolders).

A question for the folder annotation: can someone provide a URL that will be clickable (if they enter that within the text box)?

**Comment by mattpetrucci** [comment]
Attached are the study metadata that we agreed on. 

<img width="466" alt="Screenshot 2023-03-22 at 2 33 17 PM" src="https://user-images.githubusercontent.com/48534856/227043482-2379433f-7f9a-4242-ac2e-15a3148bbe2f.png">

@jenhicks Regarding the complete set of annotations that we wanted to add to the study folders. Originally we had more fields about information about the data set (short description), preferred attribution (e.g., citation or acknowledgment), citation (bibtek or short text), grant number (if applicable). After discussing with you and Joy, we had made the decision to simplify it down to a single text field to make these easier for people getting started and less daunting. I'm personally okay with either option, I would only lean towards having separate fields to make things easier to query later.

Here is a screen shot of what we had drafted before.

<img width="829" alt="Screenshot 2023-03-22 at 2 35 32 PM" src="https://user-images.githubusercontent.com/48534856/227043882-b5d29d12-e2f8-47f4-850a-0dc2e8949579.png">

**Comment by jenhicks** [comment]
Thanks @mattpetrucci ! 

@AlbertoCasasOrtiz , I think with your recent commit, we're in pretty good shape now with having the full attribution details. My remaining question is whether you can have a clickable URL in any of the fields. If not, how difficult would that be to implement?

**Comment by jenhicks** [comment]
Given the discussion on the other issue, I added an item to include a field for the "Team" for a given study.

**Comment by AlbertoCasasOrtiz** [comment]
Citation and funding are not shown when you access another person's folder.

**Comment by AlbertoCasasOrtiz** [comment]
After a chat with @keenon, we concluded the following items should be separated issues:

- Allow user to change the name of the folder and subject (might want to make this a separate issue, as is likely more complex than other tasks listed here)
-  Add field to list the Team for a given project. Down the line we could pull in users, but for now just a list of names seems sufficient

**Comment by jenhicks** [comment]
Sounds good to me!

**Comment by AlbertoCasasOrtiz** [comment]
@jenhicks Sorry, I didn't answer this:

> My remaining question is whether you can have a clickable URL in any of the fields. If not, how difficult would that be to implement?

I can think on many different ways of doing this.

- The easiest approach would be allowing users to insert html, but this is inserting security issues to the code, it makes me think of XSS vulnerabilities.
- Another approach would be to parse the text looking for things that look like an url, but this could be problematic (What if something looks like a link, but it is a typo, or not a link?)
- An idea I had for this would be to allow users to use markdown: https://remarkjs.github.io/react-markdown/, in the same way GitHub does. This would allow users to better format their descriptions, add links, result tables... etc. However, this could take some more time to implement since it would imply to redesign some parts of he GUI to better fit long descriptions, preview how markdown will look like for users, extracting excerpts for the search functionality... etc.

**Comment by jenhicks** [comment]
Thanks for that explanation @AlbertoCasasOrtiz ... could you use a similar scheme to the way you allow users to enter websites on their profile page?

**Comment by AlbertoCasasOrtiz** [comment]
As concluded after discussing this issue with @keenon two weeks ago, new issues have been created for the following tasks:

- Allow user to change the name of the folder and subject (might want to make this a separate issue, as is likely more complex than other tasks listed here) - https://github.com/keenon/AddBiomechanics/issues/92
- Add field to list the Team for a given project. Down the line we could pull in users, but for now just a list of names seems sufficient - https://github.com/keenon/AddBiomechanics/issues/93
