### ISSUE TITLE
Streamline tags/metadata for participants and trials

### ISSUE THREAD

**Issue by jenhicks** [keenon/AddBiomechanics#44]
@mattpetrucci to provide a proposal

**Comment by AlbertoCasasOrtiz** [comment]
I will work on this with @mattpetrucci. We are thinking on using this library to allow users to search/explore the tree to select tags:

https://www.npmjs.com/package/react-dropdown-tree-select

**Comment by jenhicks** [comment]
Thanks for the great work on this!

One piece of feedback: the order that tags are displayed doesn't completely make sense. How about listing tags in alphabetical order? Or other ideas for ordering @mattpetrucci ?

**Comment by AlbertoCasasOrtiz** [comment]
I think that is a great idea and can make the search of tags easier for users.

**Comment by mattpetrucci** [comment]
Alphabetical sounds good for now. We could put the phenotypes in alphabetical order and then the subtags under each should also be alphabetical.

**Comment by mattpetrucci** [comment]
Is there a way to collapse each level? It would be nice to be able to see all the categories first and then expand out, especially for the trial tags

**Comment by AlbertoCasasOrtiz** [comment]
There is currently no way of collapsing, but since this is a custom implementation we can implement it. I don't know how difficult could it be, but it is possible.

**Comment by jenhicks** [comment]
Got it ... I think moving to alphabetical sounds like a good first step and the collapsible part could come later.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @jenhicks @mattpetrucci , I think we should close this issue and create tow new ones for sorting elements alphabetically, and for making levels collapsable. I totally forgot about this and I think it will be better if I have the two new issues in the Zenhub board.
