### ISSUE TITLE
Automatically truncate marker data to GRF data when fitting dynanics

### ISSUE THREAD

**Issue by nickbianco** [keenon/AddBiomechanics#47]
If a user uploads motion capture data from, for example, overground walking trials, the data will only have ground reaction forces for a limited time window compared to the marker data. The user opts in to fit dynamics, AddBiomechanics will by necessity create residual forces at all time points where there are no forces. This will blow up the the dynamics fitter problem and make it slow.

To avoid this, we need to truncate marker data to the ground reaction force data when the user opts in to fit dynamics. If there are multiple contiguous segments of forces within the trial, we could split up the marker data into separate trials for these force segments, which will make processing in AddBiomechanics simpler.

**Comment by carmichaelong** [comment]
Also cover case where a GRF file has a larger time range compared to the mocap file.
