### ISSUE TITLE
Richer search index (without adding a database)

### ISSUE THREAD

**Issue by keenon** [keenon/AddBiomechanics#59]
We want to be able to do richer searches, over profile names and dataset tags and descriptions. HOWEVER, we don't want to run a database (I feel very strongly about this). We also don't want the frontend to have to do any for loops over users/databases downloading hundreds of JSON files.

We already download a list of all files on S3 whenever a user loads the page. This list of all the files already contains useful information, in the form of empty "tag files" like "_SEARCH", which are 0 byte files that exist only to add an entry to the list of files that can be interpreted without needing to download any other files.

I'd like to add empty files "_FULLNAME_<user's name here>" to the user's home directory, and "_DESC_<dataset description's first 100 chars>" to the dataset folders, so that we can get that information without downloading any files. I'd like the frontend to manage these files (upload new ones when values change, and delete old ones that are out of date), and use them to support richer searches without having to download extra information beyond the list of files.

**Comment by AlbertoCasasOrtiz** [comment]
According to a conversation with @keenon , we are not doing search anymore. Closing.
