### ISSUE TITLE
Allow selection of a static trial on the web GUI

### ISSUE THREAD

**Issue by keenon** [keenon/AddBiomechanics#63]
Right now, to use a static trial in your data, you need to upload a trial named (exactly) `static`, which is both unintuitive and not clear.

What we should have instead is some sort of UI, where you can specify which of your trials, if any, are the static trial. I'm not exactly sure what UI would be the most intuitive here, so let's have a brief discussion here about it. We need to expose this feature before the class, so we should hustle to get the design decided and implemented in the next day or two.

Here are some design ideas for how we could implement this:

- This could be a drop-down multiple-select in the subject configuration that let's you choose "Select Static Trial" and then has options "[<none>, trial1, trial2, etc]".
- This could be radio-buttons on the trials themselves (like a vertical column of buttons, one on each trial) where we only allow one box to be ticked at a time.
- This could be a file drag-and-drop in the header that lets you upload a "static trial mocap" file, that's separate from your regular trials (this would require minimal changes on the backend, just have that static file be called `trials/static/markers.c3d` or `trials/static/markers.trc`

What do people think would be most intuitive?

**Comment by jenhicks** [comment]
If this is needed, I think the first or third options seem most intuitive.

**Comment by nickbianco** [comment]
I like the third option, it seems to be most in line with the current design of the website.

**Comment by keenon** [comment]
Ok, I like the third option too. I can take a stab at opening a PR for this.
