### ISSUE TITLE
Cannot see list of things to plot in the 3D visualizer

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [keenon/AddBiomechanics#65]
I was trying to visualize plots in the 3D visualizer, but everytime I try to select something to plot, I only get an xml header as an option. I attach image:

![asdf](https://user-images.githubusercontent.com/15672785/229241947-f0e0197b-f56a-4b0a-8c2a-f9e433301b39.PNG)

This is happening in both **prod** and **dev**. I have tried in my own dataset and in other people's datasets.

**Comment by AlbertoCasasOrtiz** [comment]
@keenon I have some feedback here:

The select is trying to get the values from a file called plot.csv, inside of each trial folder.

Looks like this file is not present in every trial. For example:

- This trial does not have that file: https://dev.addbiomechanics.org/data/207f3d89-0057-4907-a24b-39bea906ef42/OpenCap%20Test/Alberto-Jump?show-trial=0, wo when trying to retrieve it, it is sending a response in xml format. It tries to read this xml file, and shows the header.
- This trial does have that file: https://dev.addbiomechanics.org/data/dabfbf28-b284-420f-886b-813c95720258/Pilot%201?show-trial=0. So it correctly retrieves the values.

My guess is that at some point we changed the way in which these values are generated/stored, probably in the backend side, but not the way in which it is retrieved.

**Comment by nickbianco** [comment]
It looks like `plot.csv` is only being created if you've enabled dynamics fitting: 

https://github.com/keenon/AddBiomechanics/blob/da385f3f874cb4d2e6f4e231c539ae2fe0f6665a/server/engine/engine.py#L943

I'm not sure when that changed, or if the plotting stuff was introduced along with the dynamics fitting feature. @keenon, do you know if there's a marker fitting only way to create `plot.csv`?

**Comment by AlbertoCasasOrtiz** [comment]
Thank you @nickbianco! If this is the case and we only want users to be able to create plots if dynamics fitting is enabled, it should be easy to just don't show the "Analyze the results" select in the visualizer.

**Comment by nickbianco** [comment]
We could do that, but it would be easy enough to create a `plot.csv` file when only running marker fitting. After talking to @keenon, I'm assigning this to myself and will work on it in the upcoming spring.

**Comment by AlbertoCasasOrtiz** [comment]
Nick fixed everything in the backend, but looks like the frontend is retrieving things wrongly. I am trying to fix the bug in the frontend.
